# Generated by Django 6.1 on 2026-08-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(db_index=True)),
                ('path', models.CharField(max_length=500)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=10)),
                ('device_type', models.CharField(blank=True, max_length=30)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
